var hit = Flag_Get(FLAG_TYPE.DYNAMIC, FLAG_DYNAMIC.HIT);

if (hit <= 1)
{
	Flag_Set(FLAG_TYPE.DYNAMIC,FLAG_DYNAMIC.DIFFICULTY, BATTLE_DIFFICULTY.HARD);
}

if (hit > 1 && hit <= 4)
{ 
	Flag_Set(FLAG_TYPE.DYNAMIC,FLAG_DYNAMIC.DIFFICULTY, BATTLE_DIFFICULTY.NORMAL);
}

if (hit > 4)
{
	Flag_Set(FLAG_TYPE.DYNAMIC,FLAG_DYNAMIC.DIFFICULTY, BATTLE_DIFFICULTY.EASY);
}

Flag_Set(FLAG_TYPE.DYNAMIC, FLAG_DYNAMIC.HIT, 0);
return true;